import type { MarketplaceListing } from './types'

/** Annonces « communauté » pré-chargées pour la démo (autres créateurs). */
export const SEED_LISTINGS: MarketplaceListing[] = [
  {
    id: 'mkt-seed-1',
    pipelineId: 'seed-pipe-1',
    pipelineName: 'Réconciliation bancaire CI',
    title: 'Réconciliation bancaire — Banques CI',
    description:
      'Import CSV relevé + ledger interne, rapprochement par référence et montant, export des écarts et alertes anomalies > 500k XOF.',
    category: 'Banque',
    priceEur: 89,
    pricingModel: 'one_time',
    status: 'published',
    previewNodes: [
      { id: 'n1', slug: 'csv_reader', label: 'Relevé CSV', position: { x: 0, y: 80 } },
      { id: 'n2', slug: 'csv_reader', label: 'Ledger interne', position: { x: 0, y: 220 } },
      { id: 'n3', slug: 'join', label: 'Rapprochement', position: { x: 220, y: 150 } },
      { id: 'n4', slug: 'detect_anomalies', label: 'Anomalies', position: { x: 440, y: 150 } },
      { id: 'n5', slug: 'file_export', label: 'Export écarts', position: { x: 660, y: 150 } },
    ],
    previewEdges: [
      { source: 'n1', target: 'n3' },
      { source: 'n2', target: 'n3' },
      { source: 'n3', target: 'n4' },
      { source: 'n4', target: 'n5' },
    ],
    nodesCount: 5,
    creatorId: 'user-demo-aicha',
    creatorName: 'Aïcha Koné',
    creatorOrg: 'Banque Atlantique CI',
    publishedAt: '2026-05-12T10:00:00Z',
    demoRuns: 1240,
    successRate: 98.2,
    avgDurationSec: 42,
    installCount: 47,
    rating: 4.8,
    reviewCount: 12,
  },
  {
    id: 'mkt-seed-2',
    pipelineId: 'seed-pipe-2',
    pipelineName: 'Pack OHADA mensuel',
    title: 'Clôture comptable OHADA — mensuel',
    description:
      'Normalisation plan comptable, agrégation par classe, contrôles d\'équilibre et rapport PDF prêt pour le commissaire.',
    category: 'OHADA',
    priceEur: 149,
    pricingModel: 'subscription',
    status: 'published',
    previewNodes: [
      { id: 'a1', slug: 'csv_reader', label: 'Balance', position: { x: 0, y: 100 } },
      { id: 'a2', slug: 'filter', label: 'Classe 6-7', position: { x: 200, y: 100 } },
      { id: 'a3', slug: 'aggregate', label: 'Par compte', position: { x: 400, y: 100 } },
      { id: 'a4', slug: 'quality_report', label: 'Contrôles', position: { x: 600, y: 100 } },
    ],
    previewEdges: [
      { source: 'a1', target: 'a2' },
      { source: 'a2', target: 'a3' },
      { source: 'a3', target: 'a4' },
    ],
    nodesCount: 4,
    creatorId: 'user-demo-marc',
    creatorName: 'Marc Diallo',
    creatorOrg: 'Cabinet Diallo & Associés',
    publishedAt: '2026-04-20T14:30:00Z',
    demoRuns: 890,
    successRate: 96.5,
    avgDurationSec: 78,
    installCount: 23,
    rating: 4.6,
    reviewCount: 8,
  },
  {
    id: 'mkt-seed-3',
    pipelineId: 'seed-pipe-3',
    pipelineName: 'Détection fraude mobile money',
    title: 'Fraude Mobile Money — règles + IA',
    description:
      'Détection z-score, montants atypiques et scoring IA. Sortie enrichie is_anomaly + raison pour équipe conformité.',
    category: 'Finance',
    priceEur: 199,
    pricingModel: 'one_time',
    status: 'published',
    previewNodes: [
      { id: 'f1', slug: 'csv_reader', label: 'Transactions', position: { x: 0, y: 120 } },
      { id: 'f2', slug: 'mask_pii', label: 'Masquage PII', position: { x: 180, y: 120 } },
      { id: 'f3', slug: 'detect_anomalies', label: 'Z-score', position: { x: 360, y: 120 } },
      { id: 'f4', slug: 'ai_transform', label: 'Scoring IA', position: { x: 540, y: 120 } },
      { id: 'f5', slug: 'file_export', label: 'Alertes', position: { x: 720, y: 120 } },
    ],
    previewEdges: [
      { source: 'f1', target: 'f2' },
      { source: 'f2', target: 'f3' },
      { source: 'f3', target: 'f4' },
      { source: 'f4', target: 'f5' },
    ],
    nodesCount: 5,
    creatorId: 'user-demo-sophie',
    creatorName: 'Sophie Mensah',
    creatorOrg: 'Fintech PayAfrique',
    publishedAt: '2026-06-01T09:00:00Z',
    demoRuns: 2100,
    successRate: 99.1,
    avgDurationSec: 35,
    installCount: 61,
    rating: 4.9,
    reviewCount: 19,
  },
]
